apiVersion: 1

datasources:
  - name: ClickHouse
    uid: netstream-clickhouse
    type: grafana-clickhouse-datasource
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      secure: false
      username: ${CLICKHOUSE_RO_USER}
      defaultDatabase: ${CLICKHOUSE_DB}
    secureJsonData:
      password: ${CLICKHOUSE_RO_PASSWORD}
